import {
  AlignCenter,
  AlignLeft,
  AlignRight,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Bold,
  Check,
  ChevronDown,
  Circle,
  CircleDot,
  Copy,
  Download,
  Eraser,
  FileDown,
  FileOutput,
  FilePenLine,
  FilePlus2,
  FileSearch,
  FileSignature,
  FileSpreadsheet,
  FileText,
  FileX2,
  FolderCog,
  FormInput,
  Highlighter,
  History,
  ImagePlus,
  Italic,
  Link2,
  ListChecks,
  LoaderCircle,
  MessageSquareText,
  Minus,
  MousePointer2,
  Move,
  PaintBucket,
  Palette,
  PenLine,
  Plus,
  RectangleHorizontal,
  Redo2,
  RotateCw,
  Save,
  ScanText,
  Search,
  SendHorizontal,
  Settings2,
  ShieldCheck,
  Signature,
  Sparkles,
  Square,
  Stamp,
  Strikethrough,
  Table2,
  Trash2,
  Type,
  Underline,
  Undo2,
  Upload,
  X,
} from "lucide-react";

// Icon choices are sourced from Iconify via better-icons and exposed here as a
// single product vocabulary so landing and editor chrome stay visually aligned.
export type AppIcon = typeof MousePointer2;

export {
  AlignCenter as IconAlignCenter,
  AlignLeft as IconAlignLeft,
  AlignRight as IconAlignRight,
  ArrowLeft as IconArrowLeft,
  ArrowRight as IconArrowRight,
  ArrowUpRight as IconArrow,
  Bold as IconBold,
  Check as IconCheck,
  ChevronDown as IconChevronDown,
  Circle as IconCircle,
  CircleDot as IconRadio,
  Copy as IconCopy,
  Download as IconDownload,
  Eraser as IconWhiteout,
  FileDown as IconFileDown,
  FileOutput as IconExportFile,
  FilePenLine as IconPdfEdit,
  FilePlus2 as IconFilePlus,
  FileSearch as IconFileSearch,
  FileSignature as IconSignatureBox,
  FileSpreadsheet as IconSpreadsheet,
  FileText as IconFileText,
  FileX2 as IconFileX,
  FolderCog as IconOrganize,
  FormInput as IconFormInput,
  Highlighter as IconHighlighter,
  History as IconHistory,
  ImagePlus as IconImage,
  Italic as IconItalic,
  Link2 as IconLink,
  ListChecks as IconListChecks,
  LoaderCircle as IconLoader,
  MessageSquareText as IconNote,
  Minus as IconMinus,
  MousePointer2 as IconSelect,
  Move as IconMove,
  PaintBucket as IconPaintBucket,
  Palette as IconPalette,
  PenLine as IconPen,
  Plus as IconPlus,
  RectangleHorizontal as IconRectangle,
  Redo2 as IconRedo,
  RotateCw as IconRotate,
  Save as IconSave,
  ScanText as IconScanText,
  Search as IconSearch,
  SendHorizontal as IconSend,
  Settings2 as IconSettings,
  ShieldCheck as IconShieldCheck,
  Signature as IconSignature,
  Sparkles as IconSparkles,
  Square as IconSquare,
  Stamp as IconStamp,
  Strikethrough as IconStrikethrough,
  Table2 as IconTable,
  Trash2 as IconTrash,
  Type as IconType,
  Underline as IconUnderline,
  Undo2 as IconUndo,
  Upload as IconUpload,
  X as IconX,
};
